# Generated by Django 2.1 on 2019-10-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191026_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('id_code', models.CharField(max_length=100)),
                ('count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.CharField(max_length=100)),
                ('qr', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('needCount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('existCount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
