# Generated by Django 2.1 on 2019-10-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
