# Generated by Django 2.1 on 2019-10-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191026_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
