# Generated by Django 2.1 on 2019-10-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191026_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='id_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
