# Generated by Django 2.1 on 2019-10-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_wish_id_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.FloatField(),
        ),
    ]
