# Generated by Django 2.1 on 2019-10-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191026_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wish',
            name='existCount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wish',
            name='needCount',
            field=models.FloatField(),
        ),
    ]
