# Generated by Django 2.1 on 2019-10-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191026_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
