# Generated by Django 2.1 on 2019-10-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
