# Generated by Django 2.2.6 on 2019-10-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_order_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_product',
            new_name='Order_p',
        ),
    ]
