# Generated by Django 2.2.6 on 2019-10-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191026_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='id_code',
        ),
    ]
