# Generated by Django 2.2.6 on 2019-10-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_wish_id_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='id_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
