# Generated by Django 2.2.6 on 2019-10-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_wish_id_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='NEW', max_length=50),
        ),
    ]
