# Generated by Django 2.2.6 on 2019-10-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20191027_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='id_code',
        ),
    ]
